!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  P1: 100.0
  P2: 400.0
  correlation_window_size: 5
  disp12MaxDiff: 0
  disparity_range: 80
  fullDP: true
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      P1: 100.0
      P2: 400.0
      correlation_window_size: 5
      disp12MaxDiff: 0
      disparity_range: 80
      fullDP: true
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      min_disparity: 1
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      prefilter_cap: 63
      prefilter_size: 255
      speckle_range: 6
      speckle_size: 500
      state: true
      stereo_algorithm: 1
      texture_threshold: 0
      type: ''
      uniqueness_ratio: 0.0
    state: []
  min_disparity: 1
  prefilter_cap: 63
  prefilter_size: 255
  speckle_range: 6
  speckle_size: 500
  stereo_algorithm: 1
  texture_threshold: 0
  uniqueness_ratio: 0.0
state: []
