P1: 100.0
P2: 400.0
correlation_window_size: 5
disp12MaxDiff: 0
disparity_range: 64
fullDP: true
min_disparity: 23
prefilter_cap: 63
prefilter_size: 255
speckle_range: 6
speckle_size: 500
stereo_algorithm: 1
texture_threshold: 10
uniqueness_ratio: 15.0
